/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(cms)': RouteRecordInfo<'/(cms)', '/', Record<never, never>, Record<never, never>>,
    '/(cms)/asd': RouteRecordInfo<'/(cms)/asd', '/asd', Record<never, never>, Record<never, never>>,
    '/(cms)/dashboard': RouteRecordInfo<'/(cms)/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/(cms)/lazada-platform/': RouteRecordInfo<'/(cms)/lazada-platform/', '/lazada-platform', Record<never, never>, Record<never, never>>,
    '/(cms)/platform/': RouteRecordInfo<'/(cms)/platform/', '/platform', Record<never, never>, Record<never, never>>,
    '/(cms)/platform/[id]': RouteRecordInfo<'/(cms)/platform/[id]', '/platform/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/(cms)/tiktok-platform/': RouteRecordInfo<'/(cms)/tiktok-platform/', '/tiktok-platform', Record<never, never>, Record<never, never>>,
    '/[...error404]': RouteRecordInfo<'/[...error404]', '/:error404(.*)', { error404: ParamValue<true> }, { error404: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/sign-in': RouteRecordInfo<'/auth/sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    '/setup-2fa': RouteRecordInfo<'/setup-2fa', '/setup-2fa', Record<never, never>, Record<never, never>>,
  }
}
