import type { AirDatepickerLocale } from "air-datepicker";

const ko: AirDatepickerLocale = {
	days: ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"],
	daysShort: ["일", "월", "화", "수", "목", "금", "토"],
	daysMin: ["일", "월", "화", "수", "목", "금", "토"],
	months: [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월",
	],
	monthsShort: [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월",
	],
	today: "오늘",
	clear: "초기화",
	dateFormat: "MM/dd/yyyy",
	timeFormat: "hh:mm aa",
	firstDay: 0,
};

const vi: AirDatepickerLocale = {
	days: ["Chủ nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"],
	daysShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
	daysMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
	months: [
		"Tháng 1",
		"Tháng 2",
		"Tháng 3",
		"Tháng 4",
		"Tháng 5",
		"Tháng 6",
		"Tháng 7",
		"Tháng 8",
		"Tháng 9",
		"Tháng 10",
		"Tháng 11",
		"Tháng 12",
	],
	monthsShort: [
		"Tháng 1",
		"Tháng 2",
		"Tháng 3",
		"Tháng 4",
		"Tháng 5",
		"Tháng 6",
		"Tháng 7",
		"Tháng 8",
		"Tháng 9",
		"Tháng 10",
		"Tháng 11",
		"Tháng 12",
	],
	today: "Hôm nay",
	clear: "Xóa",
	dateFormat: "dd/MM/yyyy",
	timeFormat: "hh:mm aa",
	firstDay: 0,
};

const en: AirDatepickerLocale = {
	days: [
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday",
	],
	daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
	daysMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
	months: [
		"January",
		"February",
		"March",
		"April",
		"May",
		"June",
		"July",
		"August",
		"September",
		"October",
		"November",
		"December",
	],
	monthsShort: [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec",
	],
	today: "Today",
	clear: "Clear",
	dateFormat: "MM/dd/yyyy",
	timeFormat: "hh:mm aa",
	firstDay: 0,
};

export const inputDatetimePickerLocales = { ko, en, vi };

export const DEBOUNCE_SELECT_DATE_TIME = 500;
